steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=config.json.enc
  - --plaintext-file=config.json
  - --location=global
  - --keyring=[visioedu]
  - --key=[psw-visioedu2019]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project=visioedu', '--version=$SHORT_SHA'],