version: "2"

services:
  visioedu_app: 
    container_name: visioedu_api
    build: .
    ports: 
      - "8080:8080"
    # volumes:
    #   - .:/usr/app
    depends_on:
      - mysql
  mysql:
    container_name: visioedu_db
    image: mysql:5.7
    ports:
      - 3307:3306 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: visioedupsw2019
    volumes:
      - ./scripts/ddl:/docker-entrypoint-initdb.d
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake','--default-authentication-plugin=mysql_native_password']