version: "3"

services:
  visioedu_app: 
    build: .
    command: npm start 
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - visioedu_db_container
  visioedu_db_container:
    image: mysql:5.7
    ports:
      - 3306:3306 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: visioedupsw2019
    volumes:
      - ./scripts/visioedu_ddl.sql:/docker-entrypoint-initdb.d
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake','--default-authentication-plugin=mysql_native_password']